# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucia/CLionProjects/SistemaBedelia

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucia/CLionProjects/SistemaBedelia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucia/CLionProjects/SistemaBedelia/CMakeFiles /home/lucia/CLionProjects/SistemaBedelia/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucia/CLionProjects/SistemaBedelia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SistemaBedelia

# Build rule for target.
SistemaBedelia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SistemaBedelia
.PHONY : SistemaBedelia

# fast build rule for target.
SistemaBedelia/fast:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/build
.PHONY : SistemaBedelia/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/main.cpp.s
.PHONY : main.cpp.s

src/ClassroomsController.o: src/ClassroomsController.cpp.o

.PHONY : src/ClassroomsController.o

# target to build an object file
src/ClassroomsController.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/ClassroomsController.cpp.o
.PHONY : src/ClassroomsController.cpp.o

src/ClassroomsController.i: src/ClassroomsController.cpp.i

.PHONY : src/ClassroomsController.i

# target to preprocess a source file
src/ClassroomsController.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/ClassroomsController.cpp.i
.PHONY : src/ClassroomsController.cpp.i

src/ClassroomsController.s: src/ClassroomsController.cpp.s

.PHONY : src/ClassroomsController.s

# target to generate assembly for a file
src/ClassroomsController.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/ClassroomsController.cpp.s
.PHONY : src/ClassroomsController.cpp.s

src/ClassroomsRepo.o: src/ClassroomsRepo.cpp.o

.PHONY : src/ClassroomsRepo.o

# target to build an object file
src/ClassroomsRepo.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/ClassroomsRepo.cpp.o
.PHONY : src/ClassroomsRepo.cpp.o

src/ClassroomsRepo.i: src/ClassroomsRepo.cpp.i

.PHONY : src/ClassroomsRepo.i

# target to preprocess a source file
src/ClassroomsRepo.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/ClassroomsRepo.cpp.i
.PHONY : src/ClassroomsRepo.cpp.i

src/ClassroomsRepo.s: src/ClassroomsRepo.cpp.s

.PHONY : src/ClassroomsRepo.s

# target to generate assembly for a file
src/ClassroomsRepo.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/ClassroomsRepo.cpp.s
.PHONY : src/ClassroomsRepo.cpp.s

src/CoursesController.o: src/CoursesController.cpp.o

.PHONY : src/CoursesController.o

# target to build an object file
src/CoursesController.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/CoursesController.cpp.o
.PHONY : src/CoursesController.cpp.o

src/CoursesController.i: src/CoursesController.cpp.i

.PHONY : src/CoursesController.i

# target to preprocess a source file
src/CoursesController.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/CoursesController.cpp.i
.PHONY : src/CoursesController.cpp.i

src/CoursesController.s: src/CoursesController.cpp.s

.PHONY : src/CoursesController.s

# target to generate assembly for a file
src/CoursesController.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/CoursesController.cpp.s
.PHONY : src/CoursesController.cpp.s

src/CoursesRepo.o: src/CoursesRepo.cpp.o

.PHONY : src/CoursesRepo.o

# target to build an object file
src/CoursesRepo.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/CoursesRepo.cpp.o
.PHONY : src/CoursesRepo.cpp.o

src/CoursesRepo.i: src/CoursesRepo.cpp.i

.PHONY : src/CoursesRepo.i

# target to preprocess a source file
src/CoursesRepo.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/CoursesRepo.cpp.i
.PHONY : src/CoursesRepo.cpp.i

src/CoursesRepo.s: src/CoursesRepo.cpp.s

.PHONY : src/CoursesRepo.s

# target to generate assembly for a file
src/CoursesRepo.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/CoursesRepo.cpp.s
.PHONY : src/CoursesRepo.cpp.s

src/DTClassroom.o: src/DTClassroom.cpp.o

.PHONY : src/DTClassroom.o

# target to build an object file
src/DTClassroom.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTClassroom.cpp.o
.PHONY : src/DTClassroom.cpp.o

src/DTClassroom.i: src/DTClassroom.cpp.i

.PHONY : src/DTClassroom.i

# target to preprocess a source file
src/DTClassroom.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTClassroom.cpp.i
.PHONY : src/DTClassroom.cpp.i

src/DTClassroom.s: src/DTClassroom.cpp.s

.PHONY : src/DTClassroom.s

# target to generate assembly for a file
src/DTClassroom.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTClassroom.cpp.s
.PHONY : src/DTClassroom.cpp.s

src/DTCourse.o: src/DTCourse.cpp.o

.PHONY : src/DTCourse.o

# target to build an object file
src/DTCourse.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTCourse.cpp.o
.PHONY : src/DTCourse.cpp.o

src/DTCourse.i: src/DTCourse.cpp.i

.PHONY : src/DTCourse.i

# target to preprocess a source file
src/DTCourse.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTCourse.cpp.i
.PHONY : src/DTCourse.cpp.i

src/DTCourse.s: src/DTCourse.cpp.s

.PHONY : src/DTCourse.s

# target to generate assembly for a file
src/DTCourse.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTCourse.cpp.s
.PHONY : src/DTCourse.cpp.s

src/DTReservation.o: src/DTReservation.cpp.o

.PHONY : src/DTReservation.o

# target to build an object file
src/DTReservation.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTReservation.cpp.o
.PHONY : src/DTReservation.cpp.o

src/DTReservation.i: src/DTReservation.cpp.i

.PHONY : src/DTReservation.i

# target to preprocess a source file
src/DTReservation.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTReservation.cpp.i
.PHONY : src/DTReservation.cpp.i

src/DTReservation.s: src/DTReservation.cpp.s

.PHONY : src/DTReservation.s

# target to generate assembly for a file
src/DTReservation.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTReservation.cpp.s
.PHONY : src/DTReservation.cpp.s

src/DTStudent.o: src/DTStudent.cpp.o

.PHONY : src/DTStudent.o

# target to build an object file
src/DTStudent.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTStudent.cpp.o
.PHONY : src/DTStudent.cpp.o

src/DTStudent.i: src/DTStudent.cpp.i

.PHONY : src/DTStudent.i

# target to preprocess a source file
src/DTStudent.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTStudent.cpp.i
.PHONY : src/DTStudent.cpp.i

src/DTStudent.s: src/DTStudent.cpp.s

.PHONY : src/DTStudent.s

# target to generate assembly for a file
src/DTStudent.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DTStudent.cpp.s
.PHONY : src/DTStudent.cpp.s

src/DayOfWeek.o: src/DayOfWeek.cpp.o

.PHONY : src/DayOfWeek.o

# target to build an object file
src/DayOfWeek.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DayOfWeek.cpp.o
.PHONY : src/DayOfWeek.cpp.o

src/DayOfWeek.i: src/DayOfWeek.cpp.i

.PHONY : src/DayOfWeek.i

# target to preprocess a source file
src/DayOfWeek.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DayOfWeek.cpp.i
.PHONY : src/DayOfWeek.cpp.i

src/DayOfWeek.s: src/DayOfWeek.cpp.s

.PHONY : src/DayOfWeek.s

# target to generate assembly for a file
src/DayOfWeek.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/DayOfWeek.cpp.s
.PHONY : src/DayOfWeek.cpp.s

src/Interface.o: src/Interface.cpp.o

.PHONY : src/Interface.o

# target to build an object file
src/Interface.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/Interface.cpp.o
.PHONY : src/Interface.cpp.o

src/Interface.i: src/Interface.cpp.i

.PHONY : src/Interface.i

# target to preprocess a source file
src/Interface.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/Interface.cpp.i
.PHONY : src/Interface.cpp.i

src/Interface.s: src/Interface.cpp.s

.PHONY : src/Interface.s

# target to generate assembly for a file
src/Interface.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/Interface.cpp.s
.PHONY : src/Interface.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/StudentsController.o: src/StudentsController.cpp.o

.PHONY : src/StudentsController.o

# target to build an object file
src/StudentsController.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/StudentsController.cpp.o
.PHONY : src/StudentsController.cpp.o

src/StudentsController.i: src/StudentsController.cpp.i

.PHONY : src/StudentsController.i

# target to preprocess a source file
src/StudentsController.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/StudentsController.cpp.i
.PHONY : src/StudentsController.cpp.i

src/StudentsController.s: src/StudentsController.cpp.s

.PHONY : src/StudentsController.s

# target to generate assembly for a file
src/StudentsController.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/StudentsController.cpp.s
.PHONY : src/StudentsController.cpp.s

src/StudentsRepo.o: src/StudentsRepo.cpp.o

.PHONY : src/StudentsRepo.o

# target to build an object file
src/StudentsRepo.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/StudentsRepo.cpp.o
.PHONY : src/StudentsRepo.cpp.o

src/StudentsRepo.i: src/StudentsRepo.cpp.i

.PHONY : src/StudentsRepo.i

# target to preprocess a source file
src/StudentsRepo.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/StudentsRepo.cpp.i
.PHONY : src/StudentsRepo.cpp.i

src/StudentsRepo.s: src/StudentsRepo.cpp.s

.PHONY : src/StudentsRepo.s

# target to generate assembly for a file
src/StudentsRepo.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/StudentsRepo.cpp.s
.PHONY : src/StudentsRepo.cpp.s

src/TApproval.o: src/TApproval.cpp.o

.PHONY : src/TApproval.o

# target to build an object file
src/TApproval.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TApproval.cpp.o
.PHONY : src/TApproval.cpp.o

src/TApproval.i: src/TApproval.cpp.i

.PHONY : src/TApproval.i

# target to preprocess a source file
src/TApproval.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TApproval.cpp.i
.PHONY : src/TApproval.cpp.i

src/TApproval.s: src/TApproval.cpp.s

.PHONY : src/TApproval.s

# target to generate assembly for a file
src/TApproval.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TApproval.cpp.s
.PHONY : src/TApproval.cpp.s

src/TClassroom.o: src/TClassroom.cpp.o

.PHONY : src/TClassroom.o

# target to build an object file
src/TClassroom.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TClassroom.cpp.o
.PHONY : src/TClassroom.cpp.o

src/TClassroom.i: src/TClassroom.cpp.i

.PHONY : src/TClassroom.i

# target to preprocess a source file
src/TClassroom.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TClassroom.cpp.i
.PHONY : src/TClassroom.cpp.i

src/TClassroom.s: src/TClassroom.cpp.s

.PHONY : src/TClassroom.s

# target to generate assembly for a file
src/TClassroom.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TClassroom.cpp.s
.PHONY : src/TClassroom.cpp.s

src/TClassroomReservation.o: src/TClassroomReservation.cpp.o

.PHONY : src/TClassroomReservation.o

# target to build an object file
src/TClassroomReservation.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TClassroomReservation.cpp.o
.PHONY : src/TClassroomReservation.cpp.o

src/TClassroomReservation.i: src/TClassroomReservation.cpp.i

.PHONY : src/TClassroomReservation.i

# target to preprocess a source file
src/TClassroomReservation.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TClassroomReservation.cpp.i
.PHONY : src/TClassroomReservation.cpp.i

src/TClassroomReservation.s: src/TClassroomReservation.cpp.s

.PHONY : src/TClassroomReservation.s

# target to generate assembly for a file
src/TClassroomReservation.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TClassroomReservation.cpp.s
.PHONY : src/TClassroomReservation.cpp.s

src/TCourse.o: src/TCourse.cpp.o

.PHONY : src/TCourse.o

# target to build an object file
src/TCourse.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TCourse.cpp.o
.PHONY : src/TCourse.cpp.o

src/TCourse.i: src/TCourse.cpp.i

.PHONY : src/TCourse.i

# target to preprocess a source file
src/TCourse.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TCourse.cpp.i
.PHONY : src/TCourse.cpp.i

src/TCourse.s: src/TCourse.cpp.s

.PHONY : src/TCourse.s

# target to generate assembly for a file
src/TCourse.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TCourse.cpp.s
.PHONY : src/TCourse.cpp.s

src/TDate.o: src/TDate.cpp.o

.PHONY : src/TDate.o

# target to build an object file
src/TDate.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TDate.cpp.o
.PHONY : src/TDate.cpp.o

src/TDate.i: src/TDate.cpp.i

.PHONY : src/TDate.i

# target to preprocess a source file
src/TDate.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TDate.cpp.i
.PHONY : src/TDate.cpp.i

src/TDate.s: src/TDate.cpp.s

.PHONY : src/TDate.s

# target to generate assembly for a file
src/TDate.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TDate.cpp.s
.PHONY : src/TDate.cpp.s

src/TStudent.o: src/TStudent.cpp.o

.PHONY : src/TStudent.o

# target to build an object file
src/TStudent.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TStudent.cpp.o
.PHONY : src/TStudent.cpp.o

src/TStudent.i: src/TStudent.cpp.i

.PHONY : src/TStudent.i

# target to preprocess a source file
src/TStudent.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TStudent.cpp.i
.PHONY : src/TStudent.cpp.i

src/TStudent.s: src/TStudent.cpp.s

.PHONY : src/TStudent.s

# target to generate assembly for a file
src/TStudent.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TStudent.cpp.s
.PHONY : src/TStudent.cpp.s

src/TTime.o: src/TTime.cpp.o

.PHONY : src/TTime.o

# target to build an object file
src/TTime.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TTime.cpp.o
.PHONY : src/TTime.cpp.o

src/TTime.i: src/TTime.cpp.i

.PHONY : src/TTime.i

# target to preprocess a source file
src/TTime.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TTime.cpp.i
.PHONY : src/TTime.cpp.i

src/TTime.s: src/TTime.cpp.s

.PHONY : src/TTime.s

# target to generate assembly for a file
src/TTime.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TTime.cpp.s
.PHONY : src/TTime.cpp.s

src/TTranscript.o: src/TTranscript.cpp.o

.PHONY : src/TTranscript.o

# target to build an object file
src/TTranscript.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TTranscript.cpp.o
.PHONY : src/TTranscript.cpp.o

src/TTranscript.i: src/TTranscript.cpp.i

.PHONY : src/TTranscript.i

# target to preprocess a source file
src/TTranscript.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TTranscript.cpp.i
.PHONY : src/TTranscript.cpp.i

src/TTranscript.s: src/TTranscript.cpp.s

.PHONY : src/TTranscript.s

# target to generate assembly for a file
src/TTranscript.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/TTranscript.cpp.s
.PHONY : src/TTranscript.cpp.s

src/adminInterface.o: src/adminInterface.cpp.o

.PHONY : src/adminInterface.o

# target to build an object file
src/adminInterface.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/adminInterface.cpp.o
.PHONY : src/adminInterface.cpp.o

src/adminInterface.i: src/adminInterface.cpp.i

.PHONY : src/adminInterface.i

# target to preprocess a source file
src/adminInterface.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/adminInterface.cpp.i
.PHONY : src/adminInterface.cpp.i

src/adminInterface.s: src/adminInterface.cpp.s

.PHONY : src/adminInterface.s

# target to generate assembly for a file
src/adminInterface.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/adminInterface.cpp.s
.PHONY : src/adminInterface.cpp.s

src/studentInterface.o: src/studentInterface.cpp.o

.PHONY : src/studentInterface.o

# target to build an object file
src/studentInterface.cpp.o:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/studentInterface.cpp.o
.PHONY : src/studentInterface.cpp.o

src/studentInterface.i: src/studentInterface.cpp.i

.PHONY : src/studentInterface.i

# target to preprocess a source file
src/studentInterface.cpp.i:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/studentInterface.cpp.i
.PHONY : src/studentInterface.cpp.i

src/studentInterface.s: src/studentInterface.cpp.s

.PHONY : src/studentInterface.s

# target to generate assembly for a file
src/studentInterface.cpp.s:
	$(MAKE) -f CMakeFiles/SistemaBedelia.dir/build.make CMakeFiles/SistemaBedelia.dir/src/studentInterface.cpp.s
.PHONY : src/studentInterface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SistemaBedelia"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ClassroomsController.o"
	@echo "... src/ClassroomsController.i"
	@echo "... src/ClassroomsController.s"
	@echo "... src/ClassroomsRepo.o"
	@echo "... src/ClassroomsRepo.i"
	@echo "... src/ClassroomsRepo.s"
	@echo "... src/CoursesController.o"
	@echo "... src/CoursesController.i"
	@echo "... src/CoursesController.s"
	@echo "... src/CoursesRepo.o"
	@echo "... src/CoursesRepo.i"
	@echo "... src/CoursesRepo.s"
	@echo "... src/DTClassroom.o"
	@echo "... src/DTClassroom.i"
	@echo "... src/DTClassroom.s"
	@echo "... src/DTCourse.o"
	@echo "... src/DTCourse.i"
	@echo "... src/DTCourse.s"
	@echo "... src/DTReservation.o"
	@echo "... src/DTReservation.i"
	@echo "... src/DTReservation.s"
	@echo "... src/DTStudent.o"
	@echo "... src/DTStudent.i"
	@echo "... src/DTStudent.s"
	@echo "... src/DayOfWeek.o"
	@echo "... src/DayOfWeek.i"
	@echo "... src/DayOfWeek.s"
	@echo "... src/Interface.o"
	@echo "... src/Interface.i"
	@echo "... src/Interface.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/StudentsController.o"
	@echo "... src/StudentsController.i"
	@echo "... src/StudentsController.s"
	@echo "... src/StudentsRepo.o"
	@echo "... src/StudentsRepo.i"
	@echo "... src/StudentsRepo.s"
	@echo "... src/TApproval.o"
	@echo "... src/TApproval.i"
	@echo "... src/TApproval.s"
	@echo "... src/TClassroom.o"
	@echo "... src/TClassroom.i"
	@echo "... src/TClassroom.s"
	@echo "... src/TClassroomReservation.o"
	@echo "... src/TClassroomReservation.i"
	@echo "... src/TClassroomReservation.s"
	@echo "... src/TCourse.o"
	@echo "... src/TCourse.i"
	@echo "... src/TCourse.s"
	@echo "... src/TDate.o"
	@echo "... src/TDate.i"
	@echo "... src/TDate.s"
	@echo "... src/TStudent.o"
	@echo "... src/TStudent.i"
	@echo "... src/TStudent.s"
	@echo "... src/TTime.o"
	@echo "... src/TTime.i"
	@echo "... src/TTime.s"
	@echo "... src/TTranscript.o"
	@echo "... src/TTranscript.i"
	@echo "... src/TTranscript.s"
	@echo "... src/adminInterface.o"
	@echo "... src/adminInterface.i"
	@echo "... src/adminInterface.s"
	@echo "... src/studentInterface.o"
	@echo "... src/studentInterface.i"
	@echo "... src/studentInterface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

